USE master
GO
DROP DATABASE DE01
GO
CREATE DATABASE DE01
GO
USE DE01
GO

--CAU 1:
CREATE TABLE TACGIA
(
	MaTG char(5) NOT NULL,
	HoTen varchar(20), 
	DiaChi varchar(50),
	NgSinh smalldatetime,
	SoDT varchar(15)
	CONSTRAINT PK_TACGIA PRIMARY KEY (MaTG)
);

CREATE TABLE SACH
(
	MaSach char(5) NOT NULL,
	TenSach varchar(25),
	TheLoai varchar(25),
	CONSTRAINT PK_SACH PRIMARY KEY (MaSach)
);

CREATE TABLE TACGIA_SACH
(
	MaTG char(5) NOT NULL,
	MaSach char(5) NOT NULL,
	CONSTRAINT PK_TACGIA_SACH PRIMARY KEY (MaTG, MaSach),
	CONSTRAINT FK_TGS_TACGIA FOREIGN KEY (MaTG) REFERENCES TACGIA(MaTG),
	CONSTRAINT FK_TGS_SACH FOREIGN KEY (MaSach) REFERENCES SACH(MaSach)
);

CREATE TABLE PHATHANH
(
	MaPH char(5) NOT NULL,
	MaSach char(5),
	NgayPH smalldatetime,
	SoLuong int,
	NhaXuatBan varchar(20),
	CONSTRAINT PK_PHATHANH PRIMARY KEY (MaPH),
	CONSTRAINT FK_PHATHANH_SACH FOREIGN KEY (MaSach) REFERENCES SACH(MaSach)
);

--CAU 2:
----CAU 2.1:
GO
CREATE TRIGGER trg_ins_upd_phathanh ON PHATHANH
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @NGAYPH smalldatetime,
			@MASACH char(5),
			@NGSINH smalldatetime

	SELECT @NGAYPH = NgayPH, @MASACH = MaSach
	FROM inserted

	SELECT @NGSINH = NgSinh
	FROM TACGIA
	INNER JOIN TACGIA_SACH ON TACGIA_SACH.MaTG = TACGIA.MaTG
	INNER JOIN PHATHANH ON PHATHANH.MaSach = TACGIA_SACH.MaSach
	WHERE PHATHANH.MaSach = @MASACH

	IF(@NGAYPH < @NGSINH)
	BEGIN
		ROLLBACK TRAN
		PRINT 'LOI: NGAY PHAT HANH PHAI LON HON NGAY SINH CUA TAC GIA'
	END
	ELSE
		PRINT 'THEM / CAP NHAT THANH CONG'
END

GO 
CREATE TRIGGER trg_upd_tacgia ON TACGIA
FOR UPDATE
AS 
BEGIN 
	DECLARE @MATG char(5),
			@NGSINH smalldatetime,
			@NGPH smalldatetime

	SELECT @MATG = MaTG, @NGSINH = NgSinh
	FROM inserted

	SELECT @NGPH = NgayPH
	FROM PHATHANH
	INNER JOIN TACGIA_SACH ON TACGIA_SACH.MaSach = PHATHANH.MaSach
	INNER JOIN TACGIA ON TACGIA.MaTG = TACGIA_SACH.MaTG
	WHERE TACGIA.MaTG = @MATG

	IF(@NGPH < @NGSINH)
	BEGIN 
		ROLLBACK TRAN
		PRINT 'LOI: NGAY SINH CUA TAC GIA PHAI NHO HON NGAY PHAT HANH SACH'
	END
	ELSE
		PRINT 'CAP NHAT THANH CONG'
END

----CAU 2.2:
GO 
CREATE TRIGGER trg_ins_upd_nxb ON PHATHANH
FOR INSERT, UPDATE
AS 
BEGIN
	DECLARE @MASACH char(5),
			@THELOAI varchar(25),
			@NHAXUATBAN varchar(20)

	SELECT @MASACH = MaSach, @NHAXUATBAN = NhaXuatBan
	FROM inserted

	SELECT @THELOAI = TheLoai 
	FROM SACH
	INNER JOIN PHATHANH ON SACH.MaSach = PHATHANH.MaSach
	WHERE PHATHANH.MaSach = @MASACH

	IF(@THELOAI = N'Giáo khoa' AND @NHAXUATBAN != N'Giáo dục')
	BEGIN
		ROLLBACK TRAN
		PRINT 'LOI: SACH GIAO KHOA CHI DO NHA XUAT BAN GIAO DUC PHAT HANH'
	END
	ELSE
		PRINT 'THEM / CAP NHAT THANH CONG'
END

GO 
CREATE TRIGGER trg_upd_theloai ON SACH
FOR UPDATE
AS 
BEGIN
	DECLARE @MASACH char(5),
			@THELOAI varchar(25),
			@NHAXUATBAN varchar(20)

	SELECT @MASACH = MaSach, @THELOAI = TheLoai
	FROM inserted

	SELECT @NHAXUATBAN = NhaXuatBan
	FROM PHATHANH
	INNER JOIN SACH ON SACH.MaSach = PHATHANH.MaSach
	WHERE PHATHANH.MaSach = @MASACH

	IF(@THELOAI = N'Giáo khoa' AND @NHAXUATBAN != N'Giáo dục')
	BEGIN
		ROLLBACK TRAN
		PRINT 'LOI: SACH GIAO KHOA CHI DO NHA XUAT BAN GIAO DUC PHAT HANH'
	END
	ELSE
		PRINT 'CAP NHAT THANH CONG'
END

--CAU 3:
----CAU 3.1:
GO
SELECT TACGIA.MaTG, HoTen, SoDT 
FROM TACGIA
INNER JOIN TACGIA_SACH ON TACGIA_SACH.MaTG = TACGIA.MaTG
INNER JOIN PHATHANH ON PHATHANH.MaSach = TACGIA_SACH.MaSach
INNER JOIN SACH ON SACH.MaSach = TACGIA_SACH.MaSach
WHERE TheLoai = N'Văn học' AND NhaXuatBan = N'Trẻ'

----CAU 3.2:
SELECT TOP 1 WITH TIES NhaXuatBan 
FROM PHATHANH
INNER JOIN SACH ON SACH.MaSach = PHATHANH.MaSach
GROUP BY NhaXuatBan
ORDER BY COUNT(TheLoai) DESC

----CAU 3.3:
SELECT PH.NhaXuatBan, TG.MaTG, HoTen 
FROM TACGIA TG
INNER JOIN TACGIA_SACH TS ON TS.MaTG = TG.MaTG
INNER JOIN PHATHANH PH ON PH.MaSach = TS.MaSach
GROUP BY PH.NhaXuatBan, TG.MaTG, HoTen
HAVING COUNT(PH.MaSach) >= ALL(SELECT COUNT(PH1.MaSach)
							   FROM TACGIA TG1
							   INNER JOIN TACGIA_SACH TS1 ON TS1.MaTG = TG1.MaTG
							   INNER JOIN PHATHANH PH1 ON PH1.MaSach = TS1.MaSach 
							   WHERE PH1.NhaXuatBan = PH.NhaXuatBan
							   GROUP BY PH1.NhaXuatBan, TG1.MaTG)


